// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartButtonPDP from "./islands/AddToCartButtonPDP.tsx";
import * as $CustomSearchBar from "./islands/CustomSearchBar.tsx";
import * as $NavItemIsland from "./islands/NavItemIsland.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $ProductDescription from "./islands/ProductDescription.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartButtonPDP.tsx": $AddToCartButtonPDP,
    "./islands/CustomSearchBar.tsx": $CustomSearchBar,
    "./islands/NavItemIsland.tsx": $NavItemIsland,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/ProductDescription.tsx": $ProductDescription,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
