// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/minicart/submit.ts";
import * as $$$$$$$$$1 from "./actions/newsletter/subscribe.ts";
import * as $$$$$$$$$2 from "./actions/wishlist/submit.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/vtex.ts";
import * as $$$$$$$$$$$3 from "./apps/site.ts";
import * as $$$1 from "./loaders/availableIcons.ts";
import * as $$$2 from "./loaders/canonical-advanced.ts";
import * as $$$3 from "./loaders/flags-config.ts";
import * as $$$4 from "./loaders/icons.ts";
import * as $$$5 from "./loaders/minicart.ts";
import * as $$$6 from "./loaders/product-canonical-advanced.ts";
import * as $$$0 from "./loaders/SearchInline.tsx";
import * as $$$7 from "./loaders/user.ts";
import * as $$$8 from "./loaders/wishlist.ts";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Brand/BrandGrid.tsx";
import * as $$$$$$2 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$3 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$4 from "./sections/Component.tsx";
import * as $$$$$$5 from "./sections/Content/BannerFaixa.tsx";
import * as $$$$$$6 from "./sections/Content/BannerMosaic.tsx";
import * as $$$$$$7 from "./sections/Content/Benefits.tsx";
import * as $$$$$$8 from "./sections/Content/Faq.tsx";
import * as $$$$$$9 from "./sections/Content/Hero.tsx";
import * as $$$$$$10 from "./sections/Content/Intro.tsx";
import * as $$$$$$11 from "./sections/Content/Logos.tsx";
import * as $$$$$$12 from "./sections/Content/OurStores.tsx";
import * as $$$$$$13 from "./sections/Content/PromoCountdownBanner.tsx";
import * as $$$$$$14 from "./sections/Content/TrustvoxCarousel.tsx";
import * as $$$$$$15 from "./sections/Content/VideoWithBackground.tsx";
import * as $$$$$$16 from "./sections/Footer/Footer.tsx";
import * as $$$$$$17 from "./sections/Header/Header.tsx";
import * as $$$$$$18 from "./sections/Images/Banner.tsx";
import * as $$$$$$19 from "./sections/Images/BannerCategory.tsx";
import * as $$$$$$20 from "./sections/Images/Carousel.tsx";
import * as $$$$$$21 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$22 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$23 from "./sections/Institucional/BannerInstitucional.tsx";
import * as $$$$$$24 from "./sections/Institucional/NossaHistoria.tsx";
import * as $$$$$$25 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$26 from "./sections/Miscellaneous/Bonifiq.tsx";
import * as $$$$$$27 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$28 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$29 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$30 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$31 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$32 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$33 from "./sections/Product/ProductShelfWithBackground.tsx";
import * as $$$$$$34 from "./sections/Product/ProductShelfWithBanner.tsx";
import * as $$$$$$35 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$36 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$37 from "./sections/Product/TrustvoxCertificate.tsx";
import * as $$$$$$38 from "./sections/Product/TrustvoxClickableRating.tsx";
import * as $$$$$$39 from "./sections/Product/TrustvoxCollector.tsx";
import * as $$$$$$40 from "./sections/Product/TrustvoxDebug.tsx";
import * as $$$$$$41 from "./sections/Product/TrustvoxDebugStars.tsx";
import * as $$$$$$42 from "./sections/Product/TrustvoxRatingWidget.tsx";
import * as $$$$$$43 from "./sections/Product/TrustvoxReviews.tsx";
import * as $$$$$$44 from "./sections/Product/TrustvoxSeal.tsx";
import * as $$$$$$45 from "./sections/Product/TrustvoxStars.tsx";
import * as $$$$$$46 from "./sections/Product/TrustvoxTest.tsx";
import * as $$$$$$47 from "./sections/Product/TrustvoxWidget.tsx";
import * as $$$$$$48 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$49 from "./sections/SelosSeguranca.tsx";
import * as $$$$$$50 from "./sections/Seo/AdvancedCanonical.tsx";
import * as $$$$$$51 from "./sections/Session.tsx";
import * as $$$$$$52 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$53 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$54 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/availableIcons.ts": $$$1,
    "site/loaders/canonical-advanced.ts": $$$2,
    "site/loaders/flags-config.ts": $$$3,
    "site/loaders/icons.ts": $$$4,
    "site/loaders/minicart.ts": $$$5,
    "site/loaders/product-canonical-advanced.ts": $$$6,
    "site/loaders/SearchInline.tsx": $$$0,
    "site/loaders/user.ts": $$$7,
    "site/loaders/wishlist.ts": $$$8,
  },
  "sections": {
    "site/sections/Animation/Animation.tsx": $$$$$$0,
    "site/sections/Brand/BrandGrid.tsx": $$$$$$1,
    "site/sections/Category/CategoryBanner.tsx": $$$$$$2,
    "site/sections/Category/CategoryGrid.tsx": $$$$$$3,
    "site/sections/Component.tsx": $$$$$$4,
    "site/sections/Content/BannerFaixa.tsx": $$$$$$5,
    "site/sections/Content/BannerMosaic.tsx": $$$$$$6,
    "site/sections/Content/Benefits.tsx": $$$$$$7,
    "site/sections/Content/Faq.tsx": $$$$$$8,
    "site/sections/Content/Hero.tsx": $$$$$$9,
    "site/sections/Content/Intro.tsx": $$$$$$10,
    "site/sections/Content/Logos.tsx": $$$$$$11,
    "site/sections/Content/OurStores.tsx": $$$$$$12,
    "site/sections/Content/PromoCountdownBanner.tsx": $$$$$$13,
    "site/sections/Content/TrustvoxCarousel.tsx": $$$$$$14,
    "site/sections/Content/VideoWithBackground.tsx": $$$$$$15,
    "site/sections/Footer/Footer.tsx": $$$$$$16,
    "site/sections/Header/Header.tsx": $$$$$$17,
    "site/sections/Images/Banner.tsx": $$$$$$18,
    "site/sections/Images/BannerCategory.tsx": $$$$$$19,
    "site/sections/Images/Carousel.tsx": $$$$$$20,
    "site/sections/Images/ImageGallery.tsx": $$$$$$21,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$22,
    "site/sections/Institucional/BannerInstitucional.tsx": $$$$$$23,
    "site/sections/Institucional/NossaHistoria.tsx": $$$$$$24,
    "site/sections/Links/LinkTree.tsx": $$$$$$25,
    "site/sections/Miscellaneous/Bonifiq.tsx": $$$$$$26,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$27,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$28,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$29,
    "site/sections/Product/ProductDetails.tsx": $$$$$$30,
    "site/sections/Product/ProductShelf.tsx": $$$$$$31,
    "site/sections/Product/ProductShelfTabbed.tsx": $$$$$$32,
    "site/sections/Product/ProductShelfWithBackground.tsx": $$$$$$33,
    "site/sections/Product/ProductShelfWithBanner.tsx": $$$$$$34,
    "site/sections/Product/SearchResult.tsx": $$$$$$35,
    "site/sections/Product/ShelfWithImage.tsx": $$$$$$36,
    "site/sections/Product/TrustvoxCertificate.tsx": $$$$$$37,
    "site/sections/Product/TrustvoxClickableRating.tsx": $$$$$$38,
    "site/sections/Product/TrustvoxCollector.tsx": $$$$$$39,
    "site/sections/Product/TrustvoxDebug.tsx": $$$$$$40,
    "site/sections/Product/TrustvoxDebugStars.tsx": $$$$$$41,
    "site/sections/Product/TrustvoxRatingWidget.tsx": $$$$$$42,
    "site/sections/Product/TrustvoxReviews.tsx": $$$$$$43,
    "site/sections/Product/TrustvoxSeal.tsx": $$$$$$44,
    "site/sections/Product/TrustvoxStars.tsx": $$$$$$45,
    "site/sections/Product/TrustvoxTest.tsx": $$$$$$46,
    "site/sections/Product/TrustvoxWidget.tsx": $$$$$$47,
    "site/sections/Product/Wishlist.tsx": $$$$$$48,
    "site/sections/SelosSeguranca.tsx": $$$$$$49,
    "site/sections/Seo/AdvancedCanonical.tsx": $$$$$$50,
    "site/sections/Session.tsx": $$$$$$51,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$52,
    "site/sections/Social/WhatsApp.tsx": $$$$$$53,
    "site/sections/Theme/Theme.tsx": $$$$$$54,
  },
  "actions": {
    "site/actions/minicart/submit.ts": $$$$$$$$$0,
    "site/actions/newsletter/subscribe.ts": $$$$$$$$$1,
    "site/actions/wishlist/submit.ts": $$$$$$$$$2,
  },
  "apps": {
    "site/apps/deco/analytics.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/deco/vtex.ts": $$$$$$$$$$$2,
    "site/apps/site.ts": $$$$$$$$$$$3,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
